### ISSUE TITLE
Draw method enhancements 

### ISSUE THREAD

**Issue by emil-balashov** [Borderless360/django-logic#17]
- [x] support in progress states 
- [ ] highlight begin
- [x] fix bug with process name 
- [ ] fix bug which duplicated condition on the graph, e.g. `has_no_sales_invoices` duplicated. 
- [ ] cover by tests 

```
class InvoiceProcess(Process):
    transitions = [
        Transition(action_name='approve',
                   sources=[states.draft],
                   target=states.approved),
        Transition(action_name='void',
                   sources=[states.draft, states.approved],
                   target=states.void,
                   conditions=[has_no_sales_invoices],
                   ),
    ]
```

<img width="749" alt="Screenshot 2019-12-09 at 10 28 13 PM" src="https://user-images.githubusercontent.com/6745569/70443738-9d6fe880-1ad3-11ea-9a90-6b732031a09a.png">

**Comment by huxaiphaer** [comment]
@emil-balashov , Would mind sharing the command you used to come up with the graphical presentation above.

Thanks

**Comment by emil-balashov** [comment]
> @emil-balashov , Would mind sharing the command you used to come up with the graphical presentation above.
> 
> Thanks

Sure. That's actually available in the Readme file by this [link](https://github.com/Borderless360/django-logic#display-process).

Here is an example for a quick reference 

```
from django_logic.display import * 
from demo.process import LockerProcess
display_process(LockerProcess, state='open', skip_main_process=True)
```

**Comment by emil-balashov** [comment]
@huxaiphaer

Sure. That's actually available in the Readme file by this [link](https://github.com/Borderless360/django-logic#display-process).

Here is an example for a quick reference 

```
from django_logic.display import * 
from demo.process import LockerProcess
display_process(LockerProcess, state='open', skip_main_process=True)
```

**Comment by huxaiphaer** [comment]
Well, I thought it could a command ran in the terminal, does that mean I need to do it myself ? I configure it using that code ?

**Comment by huxaiphaer** [comment]
@emil-balashov Well, I thought it could a command ran in the terminal, does that mean I need to do it myself ? I configure it using that code ?

**Comment by emil-balashov** [comment]
@huxaiphaer yes, at this moment you need to write a script by yourself if you want to run it in the terminal.
