### ISSUE TITLE
No way to change attribute name used to bind process to a model

### ISSUE THREAD

**Issue by khamenman** [Borderless360/django-logic#28]
Process class names can be pretty long, so being able to set attribute names manually would be convenient

**Comment by emil-balashov** [comment]
I'd consider changing the mechanism to bind the process with a model to something like this: 

```
class Invoice(models.Model):
    status = models.CharField(choices=InvoiceProcess.states, default='draft', max_length=16, blank=True)
    
    process = Bind(status=InvoiceProcess)
```

So, it would mean that the `InvoiceProcess` binds with `status` field via `process` variable. 
What do you think? 
Please remember, that we also have to explicitly support multiple state fields within one model.
