### ISSUE TITLE
Accessing transitions checks their permissions despite user not being available

### ISSUE THREAD

**Issue by khamenman** [Borderless360/django-logic#31]
Accessing transition from a process like
```python
model.process.transition()
```
Results in a call to `Process.get_available_transitions`, which accepts a `user` object, which it passes to permissions to check them. However, in this case user will be `None`, because all we're doing is accessing a transition.
Essentially what this means is that all permission functions have to check whether they were passed an empty user and return `True` in this case, otherwise transitions using them cannot be called.

**Comment by emil-balashov** [comment]
@khamenman resolved this bug.
